version: "3"
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=public
  server:
    build: .
    ports: 
      - '5000:5000'
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongo/public?retryWrites=true&w=majority&authSource=admin
      - PORT=5000
    depends_on:
      - mongo
